name: main
on:
  pull_request:
  push:
env:
  GOFUMPT_VERSION: 0.7.0
  GOLANGCI_LINT_VERSION: 1.63.4
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
      with:
        cache: true
        go-version-file: go.mod
    - name: build
      run: go build ./...
    - name: test
      run: go test -race -tags=docker ./...
    - name: Check formatting
      run: |
        make format
        git diff --exit-code
    - name: Check generate
      run: |
        make generate
        git diff --exit-code
  darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
      with:
        cache: true
        go-version-file: go.mod
    - name: build
      run: go build ./...
    - name: test
      run: go test -race  ./...
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
      with:
        cache: true
        go-version-file: go.mod
    - name: build
      run: go build ./...
    - name: test
      run: go test -race ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          cache: true
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd
        with:
          version: v${{ env.GOLANGCI_LINT_VERSION }}
      - name: format
        run: make format